microsoft/Teams-AdaptiveCards-Mobile

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetViewDataSource.mm

Visual improvements requested by design team:
Increased height of choice set cell to 44 px
Additional separation between choice icon and text (8 px)
Before:
After:

[iOS] - Adaptive Cards visual Improvements and fixes

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetCompactStyleView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRDateTextField.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRMediaTarget.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTypeaheadSearchViewController.mm

Added preliminary support for visionOS targets.
**Quick list of changes**
**iOS Specific**
- Added visionOS friendly window size calculation in "_ACRChoiceSetCompactStyleView_".
- Prevent visionOS unsupported UIKit button item usage in "_ACRDateTextField_"
- Prevent visionOS unsupported UIKit button item usage in "_ACRInputRenderer_"
- Update AVAsset video playing logic in "_ACRMediaTarget_" to conditionally utilize updated AVMedia asynchronous loading method

Added preliminary support for visionOS

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m
source/ios/AdaptiveCards/ADCIOSVisualizer/resources/filebrowserHostConfig.json
source/ios/AdaptiveCards/ADCIOSVisualizer/resources/sample.json
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRColumnSetRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRegistration.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRegistration.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/PrivateHeaders/UtiliOS.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/UtiliOS.mm

Added support for responsive layout in iOS. Similar behaviour to existing Android integration (https://github.com/microsoft/AdaptiveCards-Mobile/pull/52).
**Tests using iOS visualizer**
host card container equals to 200:
host card container equals to 300:
host card container equals to 500:

[iOS] Responsive Layout integration.

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextBlockRenderer.mm

**Issue**
Adaptive Card with long text and limited number of lines displays wrong height with empty space.
**Fix**
The View is being added to the StackView before configuring the max lines, which produces bad height. Moving the addition to the end fix the problem.
**Validation**
Manual Validation
Before:
After:

[iOS] - Fixed card size with limited number of lines

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/Resources/ACRButton.xib
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/Resources/ACRButtonExpandable.xib

Adjusted colours for ACRButton to adjust luminosity ratio ( Fix for issue #47 ) 
Screenshots after fix:

[iOS] Fix for luminosity ratio on ACRButton (issue 47)

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextBlockRenderer.mm

Fixes Issue: https://github.com/microsoft/AdaptiveCards-Mobile/issues/24
A11Y voiceover announces the same piece of content twice when the accessibility label and accessibility value are the same. 
The fix is to clear the accessibility value if accessibility label and accessibility value are the same.
A11Y Inspector Before:
A11Y Inspector After:

[iOS] fix voiceover duplicates for labels

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/PrivateHeaders/UtiliOS.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/UtiliOS.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCardsTests/AdaptiveCardsUtiliOSTest.mm

Fixed parsing issue for text blocks that causes that \\* was not recognized as an asterisk on iOS. Added manual validation when the text is not an html.
Sample card payload:
`{
"type": "AdaptiveCard",
"version": "1.5",
"body": [
{
"size": "medium",
"text": "Change Contacts \\*SAMPLE TEXT\\* test",
"weight": "regular",
"type": "TextBlock"
}
],
"$schema": "http://adaptivecards.io/schemas/adaptive-card.json"
}
`
Before:
After:

[iOS] - Fixed parsing detection for asterisk.

---

source/shared/cpp/ObjectModel/ChoicesData.cpp

Added default value of AssociatedInput in ChoicesData
Default value of AssociatedInput in ChoicesData is required. Setting this value to "auto" in the constructor.

Added default value of AssociatedInput in ChoicesData

---

samples/v1.5/Scenarios/ValueChangedActionAllInputType.json
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/AutoCompleteTextViewHandler.kt
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/BaseInputHandler.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/CheckBoxSetInputHandler.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/ComboBoxInputHandler.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/DateInputHandler.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/IInputHandler.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/NumberInputHandler.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/RadioGroupInputHandler.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/RatingInputHandler.kt
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/TextInputHandler.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/TimeInputHandler.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/ToggleInputHandler.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/inputhandler/ValueChangedActionInputWatcher.kt
source/android/mobile/src/main/res/raw/importer_card.json

TimeInputHandler, DateInputHandler and NumberInputHandler extends from TextInputHandler.
resetValue called on these inputHandler results in crash because  the base implementation in TextInputHandler cast the element to TextInput.
- Removed `resetValue` from `IInputHandler`
- Added `getDefaultValue()` in `IInputHandler`
- BaseInputHandler return empty String in `getDefaultValue()`
- Other InputHandler return their own default value in `getDefaultValue()`
Added new json - ValueChangedActionAllInputType.json
[resetValue.webm](https://github.com/microsoft/AdaptiveCards-Mobile/assets/68814139/84a6686f-40a2-4019-8e9f-4f815ea47aa4)
---
[valueChange.webm](https://github.com/microsoft/AdaptiveCards-Mobile/assets/68814139/85d5cd66-fe8c-4e98-8a38-6040e300f4ac)

Change in resetValue of InputHandler

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRDateTextField.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextInputHandler.mm

We did some refactoring in Conditional Enablement of submit and execute button and now we are not getting callback for Input type text and number. The issue was in ACRTextInputHandler, _completionHandler was not initialised and hence we were not getting callback. Fixed this for both input types, also fixed am minor issue in ACRDateTextField where date gets selected on dismissing the picker and callback should happen for this too.

Conditional Enabled button fix for not getting Input Text callbacks

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextInputHandler.mm

Input type number was not getting reset to its default value if it part of valuechangedAction field of any other input type. The reason was that default value was not set, setting that in this PR.

Reseting number input to default value for value changed action

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/UtiliOS.mm

Cards that used windows style line break was adding two `<br>` tags for each \r\n instead of a single `<br>`.
`{
"type": "AdaptiveCard",
"version": "1.4",
"body": [
{
"type": "TextBlock",
"weight": "bolder",
"text": "**line1**\r\n\r\nline2\r\n\r\nline3",
"wrap": true
}
]
}`
|                | Before | After     |
| -------- | ------- | ------- |
| \r\n |  ![image](https://github.com/user-attachments/assets/782c8220-a5d3-457d-b07c-db07d300ab24) | ![image](https://github.com/user-attachments/assets/ce94b92e-53d7-40b3-abe9-9374e6ee8f11) |
| \n |    ![image](https://github.com/user-attachments/assets/ce94b92e-53d7-40b3-abe9-9374e6ee8f11)  | ![image](https://github.com/user-attachments/assets/ce94b92e-53d7-40b3-abe9-9374e6ee8f11) |
| \r    | …

[iOS] add line break support for windows style

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/RendererUtil.java

If a text contains unordered list followed by ordered list, the bullet point is not showing and replaced with numbers.
```
{
"type": "TextBlock",
"text": "1. Numbered\r- List\r",
"wrap": true
}
```
verified with the card
Before             |  After
:-------------------------:|:-------------------------:

[Android] [Bug] Fix  - Unordered list followed by ordered list not working correclty

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRCompoundButtonRenderer.mm

As based on the recent discussion and design changes, the border width of compound button should be 1px same as android

[Compound Button] Fix Border Width

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputRenderer.mm

Issue #178 
This PR fixes input action accessibility trait for links to the link trait.
See card inputsWithValidation.json (V1.5 Scenario)
I verified using accessibility inspector.

[iOS] fix input action A11Y trait for links

---

source/shared/cpp/ObjectModel/Column.cpp
source/shared/cpp/ObjectModel/Container.cpp
source/shared/cpp/ObjectModel/SharedAdaptiveCard.cpp
source/shared/cpp/ObjectModel/TableCell.cpp

If there is no area specified in area grid, then it should behave as Flow layout. This case is not handled currently. 
To fix this we added check for no area in case of Area layout. We convert to flow layout in this case.  These changes are done in all layouts: column, container, TableCell and card

Fix for no area specified in Area Grid

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContainerRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentHoldingUIView.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentHoldingUIView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRImageRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRenderer.mm

In Teams client, container with large image were not getting resized properly. There can be gap below container. It happens only in stack layout and only in Teams. 
Reverted stack layout changes in container. We will add the vertical container first then render children. 
Before we rendered all children of container then added to view group. 
Now we will add the container to view group then add children.

[iOS] Fix: Container vertical resizing may fail for large images

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputLabelView.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputLabelView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRatingInputRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRatingView.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRatingView.mm

Fixes #187
Starts inside rating input were not accessible before.  InputLableView wasn't allowing to have multiple inputs. 
We added support for it now.

[iOS]Add support for accessibility for stars in Rating Input

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextView.mm

Fix for issue https://github.com/microsoft/Teams-AdaptiveCards-Mobile/issues/167 .
After fix:

[iOS] - Fix for luminosity ratio on placeholder (issue 167)

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRichTextBlockRenderer.mm

Decreased alpha and added shadow for highlighted text to prevent non-visible text on Apple Vision Pro.
Before:
After:

[iOS] [AVP] - Fix for highlighted text not visible on Vision Pro.

---

source/android/adaptivecards/src/main/cpp/objectmodel_wrap.cpp
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/AdaptiveCardObjectModelJNI.java
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/AdaptiveCardSchemaKey.java
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/Spacing.java
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/SpacingConfig.java
source/ios/AdaptiveCards/ADCIOSVisualizer/resources/sample.json
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/UtiliOS.mm
source/shared/cpp/ObjectModel/Enums.cpp
source/shared/cpp/ObjectModel/Enums.h
source/shared/cpp/ObjectModel/HostConfig.cpp
source/shared/cpp/ObjectModel/HostConfig.h

This PR introduces "ExtraSmall" spacing for iOS.
Now spacing can contain following values.
"None", "ExtraSmall", "Small", "Default", "Medium", "Large", "ExtraLarge", "Padding"

[iOS] extra small spacing

---

samples/HostConfig/microsoft-teams-light.json
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/BadgeRenderer.kt
source/shared/cpp/ObjectModel/HostConfig.h

HorizontalAlignment property is not getting applied for badge.
Accent tint colour needs to be changed based on figma.
If the parent container is LinearLayout, gravity is added based on horizontalAlignment property
If appropriate, please include a link to a card in one of the samples directories that can be used to validate this change. This can be an existing card or a card added with this PR.
Screenshot attached

Added support for horizontal alignment in badge

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/include/ACRRatingInputDataSource.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/include/ACRRatingView.h

https://github.com/microsoft/Teams-AdaptiveCards-Mobile/issues/126
Description
This fixes a regression for SPM support by including missing headers that were recently added for ratings components. Will need to update the CI to catch these regressions ahead of time.
How Verified
I included the AdaptiveCards-Mobile sdk in an iOS project using XCode 15.2 and set the SWIFT_PACKAGE=1 preprocessor setting in my XCode Build settings and built the project.
Going forward we should add a Github Action that builds the SPM as well as enforce the symlinking of C source headers to the include directory in line with SPM needs.

[iOS] add missing ACRRating headers to include directory

---

source/shared/cpp/ObjectModel/ToggleInput.cpp

To align with desktop for toggle input wrap default behavior, when the property wrap is absent. It is default to true(See screenshot below). ADO ticket: https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/3961889
Changed the default value for wrap in toggleInput to true
`{
"$schema": "https://adaptivecards.io/schemas/adaptive-card.json",
"type": "AdaptiveCard",
"version": "1.5",
"body": [
{
"type": "TextBlock",
"text": "Toggle Input"
},
{
"type": "Input.Toggle",
"id": "acceptTerms",
"title": "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit",
"value": "true"
}
], …

[AND]Changed toggle input wrap default value to true

---

source/shared/cpp/ObjectModel/Authentication.cpp
source/shared/cpp/ObjectModel/Refresh.cpp
source/shared/cpp/ObjectModel/json/json.h

Per Office Repo policies, no warning is allowed.
All the existing test run passed. And the warning is gone.

[Shared] Fix warning in shared-libs

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetFilteredStyleView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputLabelView.mm

⚠️compiler warning: Class 'ACRInputLabelView' and 'ACRChoiceSetFilteredStyleView' do not conform to protocol 'ACRIBaseInputHandler'
Fix by adding the missing protocol methods
|before|after|
|-|-|
|<img width="697" alt="image" src="https://github.com/user-attachments/assets/54fd24ed-3c19-4ed3-9a51-6de090cc7324" /> | <img width="705" alt="image" src="https://github.com/user-attachments/assets/8bd55b9c-27e5-4a69-8d54-1c46bee70417" />|

[iOS] Fix: Add missing methods for views of ACRIBaseInputHandler

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRIBaseActionElementRenderer.h

Swift6 projects overriding custom action functions will cause compiler errors
Add swift concurrency attributes to base action protocol methods
N/A
1. In a swift6 or concurrency checking with `complete` projects
2. import the framework, subclass to ACRBaseActionElementRenderer and implement protocol functions
3. when attribute added, compiler errors are gone

[iOS] mark base actions in protocol as MainActor for swift concurrency check

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRButton.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRButton.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputRenderer.mm

Regression on button is reverted:
- Issue : Icon not appearing on button
- Root cause: This https://github.com/microsoft/Teams-AdaptiveCards-Mobile/pull/304 has removed `iconView` on button and used button configuration to show icons to fix the `deprecated warning` while using `contentEdgeInsets`.
- Changes in this PR is reverting the above PR changes only specific to ACRButton.
Tested the changes with button icons, working fine and matching with before https://github.com/microsoft/Teams-AdaptiveCards-Mobile/pull/303 :

Reverting regression in button

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRButton.mm

Button size was fixed in 2.9.16 version and when icon size is not specified icon inside button is scaled based on button text size.
Setting button text size to 15 in programmatic code to match the previous version expectation.
| 2.9.16 | Latest Main | Changes in this PR | 
|-------|-------------|--------------------|
|<img src="https://github.com/user-attachments/assets/e9f0921a-a42f-4f90-899f-5be2ac4c3375" width="240"/>| <img src="https://github.com/user-attachments/assets/183eddaa-836e-4485-bc43-d5de1950c732" width="240"/>| <img src="https://github.com/user-attachments/assets/297a9d47-b413-4a8f-ac1d-25f3a3617c7a" width="240"/>|

Button text size fixed

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRShowCardTarget.mm

Issue: Showcard flow was setting empty showcard action object and setting `card` property using `SetCard` method while rendering, this is causing all the details of show card action not available at the time of onClick event.
Fix: Setting actionElement as the original show card action element

Fixed show card flow

---

samples/v1.5/Elements/Action.Popover.json
samples/v1.5/Elements/Image.FitMode.Contain.json
samples/v1.5/Elements/Image.FitMode.Cover.json
samples/v1.5/Elements/Image.FitMode.Fill.json
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BaseActionElementRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/action/ActionSetRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ImageRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ImageRendererKt.kt
source/android/build.gradle
source/shared/cpp/ObjectModel/Image.cpp

When an image is sized using both its width and height properties, it is stretched to cover its bounding box. This can cause the aspect ratio of the image to sometimes be lost.
Added properties to Image element.
1. "fitMode": "cover/fill/contain"
2. "verticalContentAlignment": "bottom/center/top"
3. "horizontalContentAlignment": "right/center/left" 
**In fitMode as fill, it takes full width and height and image aspect ratio is not maintained in this case.**
**In fitMode as cover, smaller dimension covers the full side and other side will get cropped.  Aspect ratio is maintained in this case.**
**In fitMode as contain, larger dimension covers the full side and other side will have some empty space.  Aspect ratio is maintained in this case. Red color is shown just for testing purpose. It …

[Android] Image fitMode implemented

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRBottomSheetViewController.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRSVGImageView.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRSVGImageView.mm

ACRSVGImageView currently renders image in `UIImageRenderingModeAlwaysTemplate` mode.
This doesn't let the consumer to set the original icon color in case tintColor is not provided.
Made changes in this PR to set the original icon color in case tintColor is not provided.

Icon svg view imageRenderingMode modifications

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRButton.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACROverflowTarget.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRStringBasedKeyValueObservation.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRStringBasedKeyValueObservation.m
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/PrivateHeaders/ACRViewPrivate.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/UtiliOS.mm
source/ios/AdaptiveCards/kvo-safe-observation-fix.patch

KeyValue Observation crasher
- Add ACRStringBasedKeyValueObservation wrapper for automatic KVO cleanup
- Replace manual KVO observer management with NSMapTable-based tracking
- Integrate subscriber counting and removal guards with new safe system 
- Update all KVO observation calls to use new startObserving/stopObserving methods 
- Add dual protection: crash prevention + logical error prevention
- Maintain backward compatibility with legacy KVO interface methods 
- Fix KVO crashes caused by missing observeValueForKeyPath implementations 
- Enhance ACROverflowMenuItem with safe KVO observation management
- Additional UIImage class check as NSNull can exist in the imageViewMap mutable dictionary from ACRView.mm
This addresses KVO-related crashes in Teams Adaptive Cards Mobile v6.22.1 …

Implement safe key-value observation tracking with ACRStringBasedKeyValueObservation
