microsoft/Teams-AdaptiveCards-Mobile

.pipelines/sharedmodel-ci.yml

added shared model ci

---

source/ios/tools/AdaptiveCards.podspec

Updated podspec file version and source to 2.9.3.

Version increased to 2.9.3 for new release.

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/ChoiceSetInputRenderer.java
source/android/adaptivecards/src/main/res/values/strings.xml

https://github.com/microsoft/AdaptiveCards-Mobile/assets/23054357/b799898f-412d-4d5e-90df-b1489d6c9247

Fix spinner talkback issue for a11y

---

source/ios/tools/AdaptiveCards.podspec

Updated repository path for release.

[iOS] - Update git repository path to mobile version.

---

samples/v1.5/Scenarios/Fallback.json
samples/v1.5/Scenarios/FallbackAction.json
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/registration/CardRendererRegistration.java
source/android/mobile/src/main/java/io/adaptivecards/adaptivecardssample/MainActivityAdaptiveCardsSample.java
source/android/mobile/src/main/res/layout/content_main_activity_adaptive_cards_sample.xml
source/android/mobile/src/main/res/raw/importer_card.json

See Fallback.json and FallbackAction.json. These cards should render their fallback.

Fix android fallback

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ColumnRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ColumnSetRenderer.java

Column element is not getting focus when navigating using TAB key.  This PR addressed the focus issue on the Column elements.

[Android] [Bug] Fix Focus on Column Element

---

source/ios/tools/AdaptiveCards.podspec

Updated iOS version to 2.9.4.

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m
source/ios/tools/AdaptiveCards.podspec

Upgraded iOS version to 2.9.5 and added a minor improvement for adaptive layout in iOS Visualizer.

[iOS] - Version upgrade to 2.9.5 and minor fixes on iOS visualizer.

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/ActionLayoutRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BackgroundImageLoaderAsync.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BaseActionElementRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BaseCardElementRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/IBaseCardElementRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/InnerImageLoaderAsync.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/Util.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/ChoiceSetInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/DateInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/NumberInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/TextInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/TimeInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/ToggleInputRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ColumnRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/FactSetRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/TextBlockRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/registration/CardRendererRegistration.java
source/android/mobile/src/main/java/io/adaptivecards/adaptivecardssample/CustomObjects/Media/OnlineMediaLoader.java
source/android/mobile/src/main/java/io/adaptivecards/adaptivecardssample/MainActivityAdaptiveCardsSample.java
source/android/mobilechatapp/src/main/java/com/example/mobilechatapp/CardReaderTask.java
source/android/mobilechatapp/src/main/java/com/example/mobilechatapp/RecyclerViewContent.java

Work item: https://domoreexp.visualstudio.com/MSTeams/_workitems/edit/3534643

Add annotations and fix null textblock

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ACRChatWindow.mm
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ACVTableViewController.m
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/AdaptiveFileBrowserSource.mm
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ViewController.m
source/ios/AdaptiveCards/ADCIOSVisualizer/resources/visionOsHostConfig.json

Multiple improvements on iOS Visualizer to improve appearance on Vision OS, along minor general improvements. No logic or appearance on SDK were modified.
Screenshots:

[iOS] - Visualizer improvements for Vision OS

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetViewDataSource.mm

Adding fix for Accessibility issue on choiceset - voiceover calling required fields incorrectly as "star" instead of "required".

Fix for Accessibility issue on choiceset

---

source/ios/tools/AdaptiveCards.podspec

[iOS] - Upgrade to 2.9.6.

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer.xcodeproj/project.pbxproj

Modified bundle identifier to differentiate from old repository.

[iOS] - Modified bundle identifier to "com.Microsoft.ADCIOSVisualizer-mobile".

---

.pipelines/templates/ios-install-cert-template.yml
source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer.xcodeproj/project.pbxproj

Updates the development team string

update development team id

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/Util.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/action/ActionElementRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/input/TextInputRenderer.java
source/android/adaptivecards/src/main/res/values/strings.xml

Issues: 
1. https://github.com/microsoft/AdaptiveCards-Mobile/issues/104 
2. https://github.com/microsoft/AdaptiveCards-Mobile/issues/97
Fix a11y for openurls buttons

fix a11y for openUrl actions

---

source/ios/tools/AdaptiveCards.podspec

[iOS] - Upgrade to 2.9.7.

---

source/ios/tools/AdaptiveCards.podspec

[iOS] - Upgrade to 2.9.8.

---

AdaptiveCards.podspec

Add podspec symlink

---

samples/HostConfig/sample.json
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRCompoundButtonRenderer.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputLabelView.h
source/shared/cpp/ObjectModel/CompoundButton.cpp

This pull request primarily addresses the following key improvements:
1. **Compound Button Functionality**: Resolved the non-functioning compound button actions by appending the action attribute to the compound button class post-deserialization.
2. **Pod Update Enablement**: Facilitated pod updates on branches, allowing for a dedicated branch for CocoaPods updates, thereby enhancing internal testing capabilities.
3. **HostConfig Corrections**: Updated the hostConfig with new parameters for the compound button, ensuring accurate configuration.
4. **Compilation Error Resolution:** Rectified compilation errors encountered during the integration of this pod into another repository, thereby ensuring seamless integration.

Fix for compound Button

---

source/ios/tools/AdaptiveCards.podspec

[iOS] - Upgrade to 2.9.9.

---

source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ContainerRenderer.java

Toggle button inside a column does not announce a11y.
https://github.com/microsoft/AdaptiveCards-Mobile/issues/98 
under Samples -> ExpenseCard.Json
Locally verified.

[Android] Fixed a11y issue on Toggle Button inside a column 

---

source/ios/tools/AdaptiveCards.podspec

iOS version upgrade to 2.9.10.

[iOS] - Upgrade to 2.9.10.

---

.pipelines/android-ci.yml

Remove trigger from Android-ci

Android matching iOS ci

---

samples/HostConfig/skype.json
samples/v1.5/Scenarios/CompoundButtonSample.json
source/android/adaptivecards/src/main/cpp/objectmodel_wrap.cpp
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/AdaptiveCardObjectModelJNI.java
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/CompoundButtonConfig.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/CompoundButtonRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/registration/CardRendererRegistration.java
source/shared/cpp/ObjectModel/HostConfig.cpp
source/shared/cpp/ObjectModel/HostConfig.h

This pull requests fixes Compound Button issues with respect to,
1. Text colour for light/dark theme
2. Compound button background colour
3. Rounded corner for the compound button
4. Badge view fixes
This PR fixes compound button related issues.
If appropriate, please include a link to a card in one of the samples directories that can be used to validate this change. This can be an existing card, or a card added with this PR.
Teams Screenshots (Darl/Light mode)
How you verified the fix, including one or all of the following:
1. Tested with compound button samples with and without icons, description and badges.

Compound Button Issue Fix

---

source/ios/tools/AdaptiveCards.podspec

iOS version upgrade to 2.9.11.

[iOS] - Upgrade to 2.9.11.

---

samples/v1.4/Tests/Action.Execute.With.RegexValidation.json
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOAdaptiveCard.mm

This is a pr attempt to trigger the pipeline based off of the latest state of this PR:
https://github.com/microsoft/Teams-AdaptiveCards-Mobile/pull/220

fix: sanitize unescaped problematic url regex strings

---

source/ios/tools/AdaptiveCards.podspec

iOS version upgrade to 2.9.12.

[iOS] - Upgrade to 2.9.12. 

---

source/android/adaptivecards/src/androidTest/java/io/adaptivecards/renderer/AreaGridUtilTest.kt

Updated unit test cases for `AreaGridUtilTest`

Updated AreaGridUtilTest

---

source/ios/tools/AdaptiveCards.podspec

iOS version upgrade to 2.9.13.

[iOS] - Upgrade to 2.9.13. 

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRInputRenderer.mm

Fix for accessibility issue #192

[iOS] - Fix for accessibility on input action buttons.

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetCompactStyleView.mm

Issue #174 
This PR fixes input action accessibility trait for links to the link trait.
See card inputLabelPosition.json (V1.6 Scenario)
Verified using manual testing on physical device voiceover.

[iOS] fix A11Y for choice set view

---

source/ios/tools/AdaptiveCards.podspec

iOS version upgrade to 2.9.14.

[iOS] - Upgrade to 2.9.14.

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizerTests/ADCIOSVisualizerTests.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACOEnums.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRCarouselPageContainerView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRCarouselView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRDirectionalPanGestureRecognizer.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRDirectionalPanGestureRecognizer.m
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/PrivateHeaders/ACRCarouselView.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/PrivateHeaders/ACRDirectionalPanGestureRecognizer.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/include/ACRDirectionalPanGestureRecognizer.h
source/shared/cpp/ObjectModel/Enums.h
source/shared/cpp/ObjectModel/StyledCollectionElement.cpp

This PR involves fixes about carousel view scroll across vertical. Also fixes enum order issue

Fix Gestures conflicts

---

source/ios/tools/AdaptiveCards.podspec

iOS version upgrade to 2.9.15.

[iOS] - Upgrade to 2.9.15.

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRegistration.mm

Carousel was not working after this change - https://github.com/microsoft/Teams-AdaptiveCards-Mobile/pull/259/files#diff-eebcb344a22261063c0484f49990814854953f22e53ca9e70a132eb420366b0d

Fix for carousel not working

---

source/ios/tools/AdaptiveCards.podspec

iOS version upgrade to 2.9.16.

[iOS] - Upgrade to 2.9.16.

---

samples/HostConfig/microsoft-teams-dark.json
samples/HostConfig/microsoft-teams-light.json
samples/v1.5/Scenarios/spacing_sample.json
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/BaseCardElementRenderer.java
source/android/mobile/src/main/res/raw/importer_card.json

Adding a new Spacing type extraSmall. This value can be configured from hostConfig.
property name - spacing
value - extraSmall
`"spacing": "extraSmall",`
Added a new sample json file -  spacing_sample.json

Added support for ExtraSmall spacing in Android

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRChoiceSetCompactStyleView.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRichTextBlockRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRTextBlockRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRUILabel.mm

[iOS] - Fixed accessibility issue for empty spaces on text blocks.

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRView.mm

Add missing register case for ACRView
Add missing register case for ACRView

[iOS]Add missing register case for ACRView

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRContentStackView.mm

fix ⚠️ compiler warning: Class 'ACRContentStackView' does not conform to protocol 'ACRIContentHoldingView'

[iOS] ACRContentStackView conforms to ACRIContentHoldingView

---

source/android/adaptivecards/src/main/cpp/objectmodel_wrap.cpp
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/AdaptiveCardObjectModelJNI.java
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/BackgroundImage.java
source/android/adaptivecards/src/main/java/io/adaptivecards/objectmodel/Image.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/AdaptiveCardRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/CarouselPageRenderer.kt
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ColumnRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ContainerRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/ImageRenderer.java
source/android/adaptivecards/src/main/java/io/adaptivecards/renderer/readonly/MediaRenderer.java
source/shared/cpp/ObjectModel/BackgroundImage.cpp
source/shared/cpp/ObjectModel/BackgroundImage.h
source/shared/cpp/ObjectModel/Image.cpp
source/shared/cpp/ObjectModel/Image.h

- Adding Implementation of ThemedUrls at C++ Layer
- Enabling the same for Action Elements on Android
- Refer https://adaptivecards.microsoft.com/?topic=ThemedUrl
Samples used 
- **samples/v1.5/Elements/ThemedUrls.BackgroundImage.json**
- **samples/v1.5/Elements/ThemedUrls.Image.json**
- Android 
- Desktop
- Android
- Desktop
- Android 
- Desktop
- Android 
- Desktop

Implementation of ThemedUrls for Adaptive Card for BackgroundImage & Image Components

---

.pipelines/android-release.yml

updating pool for release builds
A Pull Request should close a **single** issue; multiple issues can be closed when the issues are **small and related**, but that should be an exception not the rule. Please keep Pull Requests small and targeted; large 'code drops' with dozens of files will be closed and asked to split into reviewable pieces. Reviews that need to be large due to dependencies will be
reviewed on a case-by-case basis.
Please use one of the well-known [github fixes keywords](https://help.github.com/en/articles/closing-issues-using-keywords) to reference
the issue fixed with this PR (eg Fixes #<github issue number>). If an issue doesn't yet exist please create one to aid
in issue tracking.
**NOTE**: For multiple issues resolved by this PR use the corresponding keywords **every …

Updated agent pool for release pipeline

---

source/ios/tools/AdaptiveCards.podspec

Upgrading iOS to 2.10.0

---

.pipelines/android-release.yml

A Pull Request should close a **single** issue; multiple issues can be closed when the issues are **small and related**, but that should be an exception not the rule. Please keep Pull Requests small and targeted; large 'code drops' with dozens of files will be closed and asked to split into reviewable pieces. Reviews that need to be large due to dependencies will be
reviewed on a case-by-case basis.
Please use one of the well-known [github fixes keywords](https://help.github.com/en/articles/closing-issues-using-keywords) to reference
the issue fixed with this PR (eg Fixes #<github issue number>). If an issue doesn't yet exist please create one to aid
in issue tracking.
**NOTE**: For multiple issues resolved by this PR use the corresponding keywords **every time** in a comma-delimited list …

Add esrp publish task

---

.pipelines/android-release.yml

A Pull Request should close a **single** issue; multiple issues can be closed when the issues are **small and related**, but that should be an exception not the rule. Please keep Pull Requests small and targeted; large 'code drops' with dozens of files will be closed and asked to split into reviewable pieces. Reviews that need to be large due to dependencies will be
reviewed on a case-by-case basis.
Please use one of the well-known [github fixes keywords](https://help.github.com/en/articles/closing-issues-using-keywords) to reference
the issue fixed with this PR (eg Fixes #<github issue number>). If an issue doesn't yet exist please create one to aid
in issue tracking.
**NOTE**: For multiple issues resolved by this PR use the corresponding keywords **every time** in a comma-delimited list …

Added md5, SHA-1, SHA256 and SHA-512

---

source/android/adaptivecards/gradle.properties

This pull request updates the version of Adaptive Cards used in the project.
Version update:
* [`source/android/adaptivecards/gradle.properties`](diffhunk://#diff-5a18e48fdfbb88c20dff41cbf403cffc1472237284970d542b941a066ddff4ffL5-R5): Updated `acVersion` from `3.1.2` to `3.7.0` to use the latest version of Adaptive Cards.# Related Issue

Update version to 3.7.0

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards.xcodeproj/project.pbxproj
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRProgressBarRenderer.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRProgressBarRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRProgressRingRenderer.h
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRProgressRingRenderer.mm
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRRegistration.mm
source/shared/cpp/ObjectModel/ProgressBar.h
source/shared/cpp/ObjectModel/ProgressRing.h

Added progress bar and progress ring support on iOS:
For now, there's no default implementation on AC SDK for Progress bar and Progress ring, will pick this up later.

[iOS] Progress bar and Progress ring

---

source/ios/tools/AdaptiveCards.podspec

Updated .podspec file.
Bumped version from 2.10.0 to 2.10.1.

[Podspec] Version bump - 2.10.1

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRToggleInputView.mm

Toggle is going out of bounds.
Before:
After:

Fixed toggle view

---

source/ios/AdaptiveCards/ADCIOSVisualizer/ADCIOSVisualizer/ACRCustomFeatureFlagResolver.m
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRProgressRingRenderer.mm

Progress ring default implementation

Progress ring default implementation

---

source/android/adaptivecards/gradle.properties

This pull request includes a minor version update for the `acVersion` property in the `gradle.properties` file.
* [`source/android/adaptivecards/gradle.properties`](diffhunk://#diff-5a18e48fdfbb88c20dff41cbf403cffc1472237284970d542b941a066ddff4ffL5-R5): Updated `acVersion` from `3.7.0` to `3.7.1`, likely indicating bug fixes or small improvements.# Related Issue
A Pull Request should close a **single** issue; multiple issues can be closed when the issues are **small and related**, but that should be an exception not the rule. Please keep Pull Requests small and targeted; large 'code drops' with dozens of files will be closed and asked to split into reviewable pieces. Reviews that need to be large due to dependencies will be
reviewed on a case-by-case basis.
Please use one of the …

Upgrade version to 3.7.1

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/ACRShowCardTarget.mm

Issue - Input validations are not happening when submit or execute is clicked inside split button bottomsheet

Fixed input validation - execute and submit inside splitbutton bottomsheet

---

source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/SwiftAdaptiveCards/Legacy/SwiftLegacyACSupportPending.swift
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/SwiftAdaptiveCards/Legacy/SwiftParseUtil.swift
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/SwiftAdaptiveCards/SwiftActionElements.swift
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/SwiftAdaptiveCards/SwiftAdaptiveCard.swift
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/SwiftAdaptiveCards/SwiftBaseElement.swift
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/SwiftAdaptiveCards/SwiftCardElements.swift
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/SwiftAdaptiveCards/SwiftContainerElements.swift
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/SwiftAdaptiveCards/SwiftInputElements.swift
source/ios/AdaptiveCards/AdaptiveCards/AdaptiveCards/SwiftAdaptiveCards/Util/SwiftEnums.swift

Just renames 'AnyCodable' to be less generic to avoid colliding with other similar implementations. Removes some misc remote diff empty files

fix: rename anycodable discard remote diff

---

source/ios/tools/AdaptiveCards.podspec

iOS version bump - 2.10.6

---

.pipelines/templates/ios-ci-template.yml

Updated iOS version from 17.5 to 18.5 in ci pipeline

Modified pipeline - changed iOS version from 17.5 to 18.5

---

source/ios/tools/AdaptiveCards.podspec

Bumped iOS version to 2.10.8
